.Тело запроса не является корректным JSON:
[source, JSON]
....
HTTP/1.1 400 Bad Request

{
  "statusCode": 400,
  "url": "/api/v1/users/me/favorites",
  "message": "некорректное тело запроса",
  "date": "2026-04-17T14:32:00Z"
}
....

.Параметр `listing_id` имеет некорректный формат UUID:
[source, JSON]
....
HTTP/1.1 400 Bad Request

{
  "statusCode": 400,
  "url": "/api/v1/users/me/favorites",
  "message": "некорректный формат listing_id",
  "date": "2026-04-17T14:32:00Z"
}
....

.JWT-токен отсутствует, невалиден или просрочен:
[source, JSON]
....
HTTP/1.1 401 Unauthorized

{
  "statusCode": 401,
  "url": "/api/v1/users/me/favorites",
  "message": "невалидный или просроченный токен",
  "date": "2026-04-17T14:32:00Z"
}
....

.Объявление с указанным `listing_id` не существует:
[source, JSON]
....
HTTP/1.1 404 Not Found

{
  "statusCode": 404,
  "url": "/api/v1/users/me/favorites",
  "message": "объявление не найдено",
  "date": "2026-04-17T14:32:00Z"
}
....

.Непредвиденная ошибка на стороне сервера:
[source, JSON]
....
HTTP/1.1 500 Internal Server Error

{
  "statusCode": 500,
  "url": "/api/v1/users/me/favorites",
  "message": "внутренняя ошибка сервера, попробуйте позже",
  "date": "2026-04-17T14:32:00Z"
}
....
