@startuml activity diagram
:4.1. Идентификация пользователя по JWT;
if (Токен валиден?) then (да)
    :4.2. Проверка роли администратора;
    if (Роль == "admin"?) then (да)
        :4.3. Параллельные запросы к БД для подсчёта агрегатов;
        if (Все запросы успешны?) then (да)
            :4.4. Формирование итогового ответа;
            #palegreen :4.5. Отправка ответа об успехе;
            stop
        else (нет)
        endif
    else (нет)
    endif
else (нет)
endif
#pink :Отправка ответа об ошибке;
stop
@enduml
