@startuml activity diagram
:4.1. Идентификация пользователя по JWT;
if (Токен валиден?) then (да)
    :4.2. Проверка роли администратора;
    if (Роль == "admin"?) then (да)
        :4.3. Валидация входных параметров;
        if (Валидация прошла успешно?) then (да)
            :4.4. Проверка уникальности пары (platform, external_id);
            if (Источник уже существует?) then (нет)
                :4.5. Создание записи в БД;
                if (Запрос успешен?) then (да)
                    :4.6. Формирование итогового ответа;
                    #palegreen :4.7. Отправка ответа об успехе;
                    stop
                else (нет)
                endif
            else (да)
            endif
        else (нет)
        endif
    else (нет)
    endif
else (нет)
endif
#pink :Отправка ответа об ошибке;
stop
@enduml
