@startuml activity diagram
:4.1. Идентификация пользователя по JWT;
if (Токен валиден?) then (да)
    :4.2. Проверка роли администратора;
    if (Роль == "admin"?) then (да)
        :4.3. Валидация входных параметров;
        if (Валидация прошла успешно?) then (да)
            :4.4. Запрос к БД на получение топа брендов;
            if (Запрос успешен?) then (да)
                :4.5. Формирование итогового ответа;
                #palegreen :4.6. Отправка ответа об успехе;
                stop
            else (нет)
            endif
        else (нет)
        endif
    else (нет)
    endif
else (нет)
endif
#pink :Отправка ответа об ошибке;
stop
@enduml
