@startuml activity diagram
:4.1. Валидация входных параметров;
if (Валидация прошла успешно?) then (да)
    :4.2. Построение условий выборки;
    :4.3. Запрос к БД на подсчёт общего количества;
    if (Запрос выполнен успешно?) then (да)
        :4.4. Запрос к БД на получение страницы объявлений;
        if (Запрос выполнен успешно?) then (да)
            :4.5. Формирование итогового ответа;
            #palegreen :4.6. Отправка ответа об успехе;
            stop
        else (нет)
        endif
    else (нет)
    endif
else (нет)
endif
#pink :Отправка ответа об ошибке;
stop
@enduml
