@startuml activity diagram
:4.1. Идентификация пользователя по JWT;
if (JWT валиден?) then (да)
    :4.2. Валидация входных параметров;
    if (Валидация прошла успешно?) then (да)
        :4.3. Удаление записи из таблицы избранного;
        if (Строка удалена?) then (да)
            #palegreen :4.4. Отправка ответа об успехе (204 No Content);
            stop
        else (нет)
        endif
    else (нет)
    endif
else (нет)
endif
#pink :Отправка ответа об ошибке;
stop
@enduml
