@startuml activity diagram
:4.1. Идентификация пользователя по JWT;
if (JWT валиден?) then (да)
    :4.2. Валидация входных параметров;
    if (Валидация прошла успешно?) then (да)
        :4.3. Запрос к БД на получение количества записей избранного;
        :4.4. Запрос к БД на получение постраничной выборки избранного;
        :4.5. Формирование итогового ответа;
        #palegreen :4.6. Отправка ответа об успехе;
        stop
    else (нет)
    endif
else (нет)
endif
#pink :Отправка ответа об ошибке;
stop
@enduml
