.Заголовок `Authorization` не передан:
[source, JSON]
....
HTTP/1.1 401 Unauthorized

{
  "statusCode": 401,
  "url": "/api/v1/auth/logout",
  "message": "отсутствует токен авторизации",
  "date": "2026-04-17T14:32:00Z"
}
....

.Заголовок `Authorization` имеет некорректный формат (не `Bearer <token>`):
[source, JSON]
....
HTTP/1.1 401 Unauthorized

{
  "statusCode": 401,
  "url": "/api/v1/auth/logout",
  "message": "неверный формат заголовка Authorization",
  "date": "2026-04-17T14:32:00Z"
}
....

.JWT подписан неподдерживаемым алгоритмом (не HMAC):
[source, JSON]
....
HTTP/1.1 401 Unauthorized

{
  "statusCode": 401,
  "url": "/api/v1/auth/logout",
  "message": "неподдерживаемый алгоритм подписи токена",
  "date": "2026-04-17T14:32:00Z"
}
....

.JWT невалидный или просроченный:
[source, JSON]
....
HTTP/1.1 401 Unauthorized

{
  "statusCode": 401,
  "url": "/api/v1/auth/logout",
  "message": "невалидный или просроченный токен",
  "date": "2026-04-17T14:32:00Z"
}
....

.В JWT отсутствует клейм `user_id`:
[source, JSON]
....
HTTP/1.1 401 Unauthorized

{
  "statusCode": 401,
  "url": "/api/v1/auth/logout",
  "message": "невалидный токен: отсутствует user_id",
  "date": "2026-04-17T14:32:00Z"
}
....

.Непредвиденная ошибка на стороне сервера:
[source, JSON]
....
HTTP/1.1 500 Internal Server Error

{
  "statusCode": 500,
  "url": "/api/v1/auth/logout",
  "message": "внутренняя ошибка сервера, попробуйте позже",
  "date": "2026-04-17T14:32:00Z"
}
....
